### ISSUE TITLE
Support compile time html() and partial() functions

### ISSUE THREAD

**Issue by tmpfs** [tmpfs/trucks#13]
The idea being to:

1. Parse DOM text nodes that match (`/^\s*\{/` and `/\}\s*$/`) to javascript AST
2. Search the AST for callee expressions using the name `html`
3. Extract the string argument as HTML
4. Compile to an immediately executed render function
5. Inject the function into the AST tree replacing `html('<span></span>')` with the compiled function

**Comment by tmpfs** [comment]
See: https://github.com/google/incremental-dom/issues/283

**Comment by tmpfs** [comment]
Initial prerequisite work for partials has been completed with the recent refactor so that the component tree has a partials list which will allow the compiler to compile and reference template partials.

**Comment by tmpfs** [comment]
Compile time HTML function added in 516ff9cdef7470de4e94bdea598fbba69f36eef7.

**Comment by tmpfs** [comment]
@treshugart

Thanks for the heads up on the `html()` issue over at incremental-dom, it gave me an idea. I wonder what you think. I figured if we parsed the call at compile time then we would still get the benefits of the incremental-dom diff/patch logic.

So we can now break into inline script within a `<template>` with calls to `html()` compiled to skate style hyperscript and thus incremental dom calls, from the [example](https://github.com/tmpfs/trucks/blob/master/doc/EXAMPLE.md) a template like this:

```html
<div class="container">
  <p class="title">${this.title}</p>
  <div class="content">
    <slot name="content"></slot>
    <ul class="items">
      <script>
        this.values.forEach((item) => {
          html("<li>${item}</li>"); 
        })
      </script>
    </ul>
  </div>
</div>
```

And the relevant part from the compiled function:

```javascript
skate.vdom.element("ul", {
  "class": "items"
}, () => {
  this.values.forEach(item => {
    skate.vdom.element("li", () => {
      skate.vdom.text(`${ item }`);
    });
  });
});
```

I am now considering a `partial()` function that could refer to another `<template>` for those instances when it would be preferable to be declarative with the markup but use it conditionally, something like:

```html
<template>
  <div>
    <script>
      this.values ? partial('content') : html('<em>No data</em>');
    </script>
  </div>
</template>
<template id="content">
<!-- partial markup content -->
</template>
```

Do you think a simple partial system is worthwhile or better just to stick to `html()`?

**Comment by tmpfs** [comment]
FYI, I would still like to support JSX in the future but as it is not HTML compliant it would need to end up in a script element, something like:

```html
<template>
<script type="application/jsx">
// JSX markup here
</script>
</template>
```

**Comment by treshugart** [comment]
So a couple of things.

I noticed that you were using `events`. We decided to remove that as it is a second way to bind events to elements in your `render()` function which can create confusion about the best way to do things. Binding events to the host element can be done in the created lifecycle. See https://github.com/skatejs/skatejs/issues/675 for more details. Events still bubble so you can delegate events even from listeners in the light DOM, but selector based delegation becomes an edge-case with this way of doing things. Hopefully this doesn't impact you too much. Happy to dicsuss.

In terms of your `partial()`, I like the idea. We recently introduced similar functionality, that you might be able to hook into instead of having to parse that. See [function helpers](https://github.com/skatejs/skatejs#function-helper). Before you could pass component constructors to a `vdom.element()` call instead of having to manually pass a tag name:

```js
const MyComponent = define('my-component', {});
// ...
vdom.element(MyComponent);
```

Now you can do something like:

```js
const list = (props, chren) => vdom.element('ul', props, chren);
const item = (props, chren) => vdom.element('li', props, chren);
// ...
vdom.element(list, () => {
  for (let a = 0; a < 10; a++) {
    vdom.element(item, { id: `item-${a}` }, `Item ${a + 1}`);
  }
});
```

That would print something like:

```html
<ul>
  <li id="item-0">Item 1</li>
  <li id="item-1">Item 2</li>
  <li id="item-2">Item 3</li>
  <li id="item-3">Item 4</li>
  <li id="item-4">Item 5</li>
  <li id="item-5">Item 6</li>
  <li id="item-6">Item 7</li>
  <li id="item-7">Item 8</li>
  <li id="item-8">Item 9</li>
  <li id="item-9">Item 10</li>
</ul>
```

Maybe instead of having to build partials you could just follow this pattern? Not sure how that would play into parsing your HTML, though.

**Comment by tmpfs** [comment]
Thanks for the information.

The change to the `events` handling is important. If I am right in thinking the one true way is using `on*` attributes then I can update to compile `on*` attributes to javascript code rather than treating them as string/template literal attributes.

The function helper information is useful although I think with the way the compiler works at the moment I don't need to use it - nice to know though :)

I implemented the `partial()` function because it was quite easy. It's a runtime inner function that looks up a prefixed compiled template in the map and invokes it in the scope of the component. I think partials are interesting as they pave the way for sharing common markup between components, I can imagine a set of components with a shared class hierarchy could have structural markup in common. 

I updated the [example](https://github.com/tmpfs/trucks/blob/master/doc/EXAMPLE.md) to use a partial and the compiled output now looks like:

```javascript
const templates = {
  "x-panel-current": function render(elem) {
    skate.vdom.element("p", () => {
      skate.vdom.text("Current language: ");
      skate.vdom.element("em", () => {
        skate.vdom.text(`${ this.lang.toLowerCase() }`);
      });
    });
  },
  "x-panel": function render(elem) {
    function partial(id) {
      return templates[elem.tagName.toLowerCase() + '-' + id].call(elem, elem);
    }

    skate.vdom.element("style", () => {
      skate.vdom.text("/*\n  Inline styles for the shadow DOM.\n*/\n* {\n  font-family: sans-serif;\n  color: white;\n}\n\np, ::content p {\n  margin: 0; \n  padding: 1em;\n}\n\n.title {\n  background: black;\n  cursor: pointer;\n}\n\n.content {\n  min-height: 10em;\n  background: gray;\n}");
    });
    skate.vdom.element("div", {
      "class": "container"
    }, () => {
      skate.vdom.element("p", {
        "class": "title"
      }, () => {
        skate.vdom.text(`${ this.title }`);
      });
      skate.vdom.element("div", {
        "class": "content"
      }, () => {
        skate.vdom.element("slot", {
          "name": "content"
        });
        skate.vdom.element("ul", {
          "class": "items"
        }, () => {
          this.values.forEach(item => {
            skate.vdom.element("li", () => {
              skate.vdom.text(`${ item }`);
            });
          });
        });

        if (this.lang) {
          partial('current');
        }
      });
    });
  }
};

function template(elem) {
  return templates[elem.tagName.toLowerCase()].call(elem, elem);
}

skate.define('x-panel', {
  props: {
    lang: {
      attribute: true 
    },
    values: {
      attribute: true,
      deserialize (val) {
        return val.split(/\s*,\s*/);
      },
      serialize (val) {
        return val.join(',');
      }
    }
  },
  events: {/* edited for brevity*/},
  render: template
});
```

**Comment by tmpfs** [comment]
@treshugart 

I've just added support for compiling on* attributes as event listeners which seems to work well with function references and arrow functions.

But I noticed that with the previous technique (`events` object) the listener signature was `(elem, e)` and now it is just the underlying DOM event `(e)` and I didn't see this mentioned in https://github.com/skatejs/skatejs/issues/675 - is it worth documenting this difference for anyone migrating? I quite liked that the component instance was passed to the event listener but I think there is probably a better way for me to be structuring the code. What would you suggest is the best way to get the reference in an event listener?

Updated code I'm testing with is in the [example](https://github.com/tmpfs/trucks/blob/master/doc/EXAMPLE.md).

**Comment by treshugart** [comment]
Since we're not delegating, you don't need `elem` anymore. Using `e.target` or `e.currentTarget` should suffice.

**Comment by treshugart** [comment]
Also note https://github.com/skatejs/skatejs/issues/694 was done before go 1.0. This will be the last breaking change before 1.0 for events (and probably everything else, too).

**Comment by tmpfs** [comment]
Thanks again for the information.

I need to update the pattern for `on` events to match https://github.com/skatejs/skatejs/issues/694.

I think I need to update my version of skatejs as when I tested `e.currentTarget` I get the paragraph element that has the event listener assigned.

Closing this issue as implemented.

**Comment by treshugart** [comment]
Ok, let me know if you have any issues doing that. I think I'm going to lowercase the first character of the event name so `onClick` and `on-click` work the same.

**Comment by tmpfs** [comment]
Actually it turned out a little weird because cheerio/htmlparser2 appear to be lowercasing the attribute names even though the docs say they shouldn't by default. I haven't worked out the source of that bug yet...

However I have worked around the issue a little bit. I like being able to use `onclick` lowercase in the HTML markup as it's idiomatic with the way these sorts of event listeners have been declared for a long time.

So I check for `on[a-z]` attributes and rewrite them to `on-` attributes.

I have updated the [example](https://github.com/tmpfs/trucks/tree/master/examples/skate-component) (which has moved) to use a prototype event as per the example in the `skatejs` readme which implies that the scope should be the component element (unless I am reading it wrong): https://github.com/skatejs/skatejs#binding-events.

However when I log `this` I get the element triggering the event (effectively `e.currentTarget`) - is that expected behaviour? Using `beta.19` now.

FWIW, lowercasing the first character of the event name makes sense so that `onClick` and `on-click` are treated the same. However, I am curious why you want to disallow `onclick`, the only reason I can come up with is allowing some attributes to begin with `on` and not be treated as events. Maybe you could clarify? Thanks.

**Comment by treshugart** [comment]
I updated the issue to match the fixed behaviour. CamelCapped is now
camelCased when bound. The rest of the name isn't altered, though. onclick
works now because it's a native prop.
